from platform_core.logging_config import get_logger
from platform_core.db import get_connection

logger = get_logger(__name__)

def replay_decision(decision_id: int) -> int:
    """
    Re-runs a past workflow interaction using the exact logged prompt,
    creating a new decision card tied to the old one via replay_id.
    
    Args:
        decision_id: The ID of the decision to replay.
        
    Returns:
        The new decision_id generated by the replay.
    """
    logger.info("Starting replay", extra={"original_decision_id": decision_id})
    
    conn = None
    try:
        conn = get_connection()
        cursor = conn.cursor()
        
        # 1. Fetch the exact original inputs from the audit log and decision card
        cursor.execute(
            """
            SELECT d.tenant_id, d.agent_name, d.action, a.prompt
            FROM decision_cards d
            JOIN audit_logs a ON d.decision_id = a.decision_id
            WHERE d.decision_id = %s
            """,
            (decision_id,)
        )
        row = cursor.fetchone()
        
        if not row:
            logger.warning(
                "Invalid replay request: Decision ID not found or has no audit log",
                extra={"decision_id": decision_id, "catch_reason": "Preventing crash on bad input ID"}
            )
            raise ValueError(f"Cannot replay decision_id {decision_id}. Not found or no audit log.")
            
        tenant_id, agent_name, action, original_prompt = row
        
        if not original_prompt:
             raise ValueError("Cannot replay because original prompt was null.")
             
        # 2. Run it through the AI Gateway again using the SDK
        from platform_core.sdk import sdk
        logger.info("Executing AI Gateway replay generation")
        
        ai_res = sdk.ai.generate(prompt=original_prompt)
        
        # 3. Save the new decision card linking back to the original via replay_id
        # We also manually set a high confidence here so the replay itself isn't blocked by the approval engine
        new_decision_id = sdk.decisions.record_decision(
            tenant_id=tenant_id,
            agent_name=agent_name,
            action=action,
            prompt=original_prompt,
            raw_output=ai_res.get("raw"),
            result=str(ai_res.get("output")),
            confidence=0.99,
            replay_id=decision_id
        )
        
        logger.info(
            "Replay completed successfully",
            extra={
                "original_decision_id": decision_id,
                "new_decision_id": new_decision_id
            }
        )
        return new_decision_id
        
    except ValueError:
        raise
    except Exception as e:
        logger.error(
            "Failed to execute replay",
            extra={
                "original_decision_id": decision_id,
                "exc_type": type(e).__name__,
                "error": str(e),
                "catch_reason": "Bubbling up error so caller knows the replay failed"
            }
        )
        raise RuntimeError(f"Replay failed: {e}")
    finally:
        if conn:
            conn.close()
